name: rankstr build and test

permissions:
  actions: write

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        target: [Debug, Release]
        mpi: [seq, par]

    name: ${{ matrix.os }}-${{ matrix.target }}-${{ matrix.mpi }}

    runs-on: ${{ matrix.os }}

    steps:

      - name: checkout
        uses: actions/checkout@v2
        with:
          path: rankstr
          fetch-depth: 0

      - name: get deps
        uses: ecp-veloc/github-actions/get-scr-os-deps@main
        with:
          os: ${{ matrix.os }}
          mpi: ${{ matrix.mpi }}

      - name: configure
        run: |
          mkdir build
          cd build
          cmake ../rankstr -DCMAKE_BUILD_TYPE=${{ matrix.target }} -DMPI=${{ matrix.mpi == 'par' }}

      - name: build
        run: |
          cd build
          make

      - name: check
        run: |
          cd build
          make check
